---
# Install Fluentd (td-agent) packages on debian based distributions.

- name: Uninstall existing Fluentd (td-agent) package.
  apt: name=td-agent state=absent

- name: Add Fluentd (TreasureData) apt key.
  apt_key:
    url: http://packages.treasuredata.com/GPG-KEY-td-agent
    state: present

- name: Add the Fluentd (TreasureData) repository.
  apt_repository: repo='deb http://packages.treasuredata.com/2/ubuntu/trusty/ trusty contrib' state=present

- name: Install Fluentd (td-agent) package.
  apt: name=td-agent update_cache=yes state=latest install_recommends=no

- name: Configure Fluentd.
  include: fluentd.yml
